/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Use Vite environment variables for client-side configuration.
// These must be provided as VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your dev environment.
const metaEnv: any = typeof import.meta !== 'undefined' ? (import.meta as any).env : {};
export const supabaseUrl: string = metaEnv?.VITE_SUPABASE_URL || '';
export const publicAnonKey: string = metaEnv?.VITE_SUPABASE_ANON_KEY || '';
export const isDevelopment: boolean = (metaEnv?.MODE === 'development') || false;