/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qwvxgdrhjtgqwwksqebf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3dnhnZHJoanRncXd3a3NxZWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNTA2NDIsImV4cCI6MjA3MzcyNjY0Mn0.A37IkjTB0pZCs1JQEuE65IL6OQt0gJk1Wt6YpVpGnKA"

// Derived exports for compatibility
export const supabaseUrl = `https://${projectId}.supabase.co`
export const isDevelopment = typeof process !== 'undefined' && process.env?.NODE_ENV === 'development'